#!/usr/bin/env bash
# measure/lib/common.sh — shell helpers for the ONE remaining shell measurement
# script, measure/fixture/make.sh. Everything else moved to measure/lib/*.py.
#
# Kept because the fixture generator was deliberately left in bash: it is 364
# lines of deterministic generation driven by a pure-integer LCG, `--verify`
# already covers it, and porting it would risk changing the fixture hash for no
# gain. It uses exactly five helpers from this file: die, ok, ensure_staging,
# require_free_space, sha256_of_stdin.
#
# Do NOT add callers. New measurement code belongs in the Python package, where
# the schema, the shared formulas and the projection are tested. This file exists
# to keep one working script working, not as a place to grow shell.
#
# Source this, don't execute it:
#   source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
#
# Every caller is expected to already be running under `set -euo pipefail`.

# Resolve this file's own directory ONCE, at source time, using BASH_SOURCE[0]
# of *this* file (not a caller's). This is what makes repo_root() work no
# matter which script sourced common.sh or what the caller's cwd is.
_COMMON_SH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# STAGING is the ONLY place scripts in this repo may write generated
# artifacts, raw capture, or run output. Never the repo tree itself — see
# CONTRIBUTING.md and the `leaks` / `verify-measurements` justfile recipes.
STAGING="${STAGING:-/private/tmp/harness-econ}"

# repo_root — absolute path to the repository root, resolved relative to this
# file's own location. Never hard-code a path here.
repo_root() {
  (cd "$_COMMON_SH_DIR/../.." && pwd)
}

# ok "name" "msg"   → "✓ name: msg" on stdout
# warn "name" "msg" → "! name: msg" on stderr, exit status untouched
# fail "name" "msg" → "✗ name: msg" on stderr
# die "name" "msg"  → fail, then exit 1
ok() {
  printf '✓ %s: %s\n' "$1" "$2"
}

# A run that completed but produced an untrustworthy number is not a failure —
# it must still be visibly distinct from one that produced a good number.
warn() {
  printf '! %s: %s\n' "$1" "$2" >&2
}

fail() {
  printf '✗ %s: %s\n' "$1" "$2" >&2
}

die() {
  fail "$1" "$2"
  exit 1
}

# require_cmd <cmd> — die with a clear message if <cmd> is not on PATH.
require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    die "require_cmd" "'$cmd' not found in PATH — install it and re-run"
  fi
}

# ensure_staging — create the staging tree. Nothing under here is ever
# committed; it exists only because the machine is nearly full and every
# script needs one place to put generated bytes.
ensure_staging() {
  mkdir -p "$STAGING/fixture" "$STAGING/raw" "$STAGING/runs"
}

# require_free_space <min_mb> <path> — die if <path>'s filesystem has less
# than <min_mb> MiB free. Default threshold 500 MB, default path $STAGING.
require_free_space() {
  local min_mb="${1:-500}"
  local path="${2:-$STAGING}"
  local probe_path="$path"
  # df needs an existing path to stat; walk up until we find one.
  while [ ! -e "$probe_path" ] && [ "$probe_path" != "/" ]; do
    probe_path="$(dirname "$probe_path")"
  done
  local avail_mb
  avail_mb="$(df -Pm "$probe_path" 2>/dev/null | awk 'NR==2 {print $4}')"
  if [ -z "${avail_mb:-}" ]; then
    die "require_free_space" "could not parse 'df -Pm $probe_path' output"
  fi
  if [ "$avail_mb" -lt "$min_mb" ]; then
    die "require_free_space" "$probe_path has ${avail_mb}MB free, need at least ${min_mb}MB"
  fi
}

# claude_version — the installed Claude Code CLI's version string.
claude_version() {
  claude --version 2>/dev/null | head -n1
}

# utc_now — current UTC timestamp, ISO-8601, second precision.
utc_now() {
  date -u +%Y-%m-%dT%H:%M:%SZ
}

# sha256_of_stdin — sha256 of whatever is piped in, as a bare lowercase hex
# digest. Prefers sha256sum (Linux/coreutils); falls back to `shasum -a 256`
# (macOS default, no coreutils required).
sha256_of_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  else
    shasum -a 256 | awk '{print $1}'
  fi
}
