#!/usr/bin/env bash
# tools/summary.sh — regenerate measurements/SUMMARY.md from every recorded
# measurement file. Run by `just summary`.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
cd "$(repo_root)"

shopt -s nullglob
files=()
for f in measurements/*.json; do
  [ "$f" = "measurements/schema.json" ] || files+=("$f")
done
out='measurements/SUMMARY.md'
{
  echo "# Measurement summary"
  echo
  echo "Generated by \`just summary\`. Do not edit by hand."
  echo
  if [ "${#files[@]}" -eq 0 ]; then
    echo "No measurements have been recorded yet."
  else
    echo "| Date | Harness | Workload | Cache-read ratio | Invalid-rep rate | Source file |"
    echo "|---|---|---|---|---|---|"
    for f in "${files[@]}"; do
      jq -r --arg src "$f" '
        [
          (.timestamp_utc // "unknown"),
          (.harness // "unknown"),
          (if (.workload | type) == "object" then (.workload.id // "unknown") else (.workload // "unknown") end),
          (.aggregates.cache_read_share // "n/a" | tostring),
          (.aggregates.invalid_rep_rate // "n/a" | tostring),
          $src
        ] | "| " + join(" | ") + " |"
      ' "$f"
    done
  fi
} >"$out"
echo "✓ summary: wrote $out"
